In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

In [3]:
cursor.execute("""
CREATE TABLE employees (
    id INTEGER,
    name TEXT,
    age INTEGER,
    department TEXT,
    salary INTEGER
);
""")

In [4]:
data = [
    (1, 'Alice', 30, 'HR', 50000),
    (2, 'Bob', 25, 'IT', 60000),
    (3, 'Charlie', 35, 'Finance', 70000),
    (4, 'Diana', 28, 'IT', 65000)
    (5, 'Ahmed', 40, 'Finance', 72000),
    (6, 'Ann', 23, 'HR', 48000),
]

cursor.executemany("INSERT INTO employees VALUES (?, ?, ?, ?, ?);", data)
conn.commit()

<>:5: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
<>:5: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_229757/2166113527.py:5: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  (4, 'Diana', 28, 'IT', 65000)

TypeError: 'tuple' object is not callable

In [5]:
data = [
    (1, 'Alice', 30, 'HR', 50000),
    (2, 'Bob', 25, 'IT', 60000),
    (3, 'Charlie', 35, 'Finance', 70000),
    (4, 'Diana', 28, 'IT', 65000),
    (5, 'Ahmed', 40, 'Finance', 72000),
    (6, 'Ann', 23, 'HR', 48000),
]

cursor.executemany("INSERT INTO employees VALUES (?, ?, ?, ?, ?);", data)
conn.commit()

In [6]:
pd.read_sql("SELECT name, salary FROM employees WHERE department = 'IT' ORDER BY salary DESC;", conn)

    name  salary
0  Diana   65000
1    Bob   60000

In [7]:
pd.read_sql("SELECT department, COUNT(*) AS employee_count FROM employees GROUP BY department;", conn)

  department  employee_count
0    Finance               2
1         HR               2
2         IT               2

In [8]:
pd.read_sql("SELECT AVG(age) AS average_age FROM employees WHERE salary > 55000;", conn)

   average_age
0         32.0

In [9]:
pd.read_sql("SELECT * FROM employees WHERE department = 'Finance' ORDER BY age ASC LIMIT 1;", conn)

   id     name  age department  salary
0   3  Charlie   35    Finance   70000

In [10]:
pd.read_sql("SELECT COUNT(*) AS count_over_30 FROM employees WHERE age > 30;", conn)

   count_over_30
0              2

In [11]:
pd.read_sql("SELECT department, SUM(salary) AS total_salary FROM employees GROUP BY department;", conn)

  department  total_salary
0    Finance        142000
1         HR         98000
2         IT        125000

In [12]:
pd.read_sql("SELECT department, AVG(salary) AS average_salary FROM employees GROUP BY department ORDER BY average_salary DESC LIMIT 1;", conn)

  department  average_salary
0    Finance         71000.0

In [13]:
data = [
    (1, 'Alice', 28, 'IT', 5500),
    (2, 'Bob', 35, 'HR', 4800),
    (3, 'Clara', 30, 'Sales', 5200),
    (4, 'Davkd', 41, 'IT', 6000),
    (5, 'Emma', 26, 'HR', 4700),
    (6, 'Frank', 33, 'Sales', 5300),
]

cursor.executemany("INSERT INTO employees VALUES (?, ?, ?, ?, ?);", data)
conn.commit()

In [14]:
pd.read_sql("SELECT * FROM employees ORDER BY salary DESC", conn)

    id     name  age department  salary
0    5    Ahmed   40    Finance   72000
1    3  Charlie   35    Finance   70000
2    4    Diana   28         IT   65000
3    2      Bob   25         IT   60000
4    1    Alice   30         HR   50000
5    6      Ann   23         HR   48000
6    4    Davkd   41         IT    6000
7    1    Alice   28         IT    5500
8    6    Frank   33      Sales    5300
9    3    Clara   30      Sales    5200
10   2      Bob   35         HR    4800
11   5     Emma   26         HR    4700

In [15]:
pd.read_sql("SELECT * FROM employees ORDER BY salary DESC LIMIT 3", conn)

   id     name  age department  salary
0   5    Ahmed   40    Finance   72000
1   3  Charlie   35    Finance   70000
2   4    Diana   28         IT   65000

In [16]:
pd.read_sql("SELECT * FROM employees WHERE department IN ('HR', 'IT')", conn

SyntaxError: incomplete input (990014872.py, line 1)

In [17]:
pd.read_sql("SELECT * FROM employees WHERE department IN ('HR', 'IT')", conn)

   id   name  age department  salary
0   1  Alice   30         HR   50000
1   2    Bob   25         IT   60000
2   4  Diana   28         IT   65000
3   6    Ann   23         HR   48000
4   1  Alice   28         IT    5500
5   2    Bob   35         HR    4800
6   4  Davkd   41         IT    6000
7   5   Emma   26         HR    4700

In [18]:
pd.read_sql("SELECT DISTINCT department FROM employees", conn)

  department
0         HR
1         IT
2    Finance
3      Sales

In [19]:
pd.read_sql("SELECT * FROM employees WHERE name LIKE 'C%'", conn)

   id     name  age department  salary
0   3  Charlie   35    Finance   70000
1   3    Clara   30      Sales    5200

In [20]:
pd.read_sql("SELECT * FROM employees ORDER BY age ASC LIMIT 2 OFFSET 2", conn)

   id   name  age department  salary
0   5   Emma   26         HR    4700
1   4  Diana   28         IT   65000